CREATE DATABASE IF NOT EXISTS projek_akhir;
USE projek_akhir;

CREATE TABLE IF NOT EXISTS tajuk (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nama_tajuk TEXT NOT NULL,
  tarikh_ditambah DATETIME DEFAULT CURRENT_TIMESTAMP
);
